FROM Python:3.14-slim

COPY requirements.txt .
RUN pip install upgrade pip && \
    pip install -r \
    requirements.txt \
    --no-cache-build
RUN rm requirements.txt

WORKDIR /app

COPY /src .

CMD ["python3", "main.py"]
